version: "3.8"
services:
  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - "$API_PORT:80"
    volumes:
      - ./avatars.conf:/etc/nginx/nginx.conf
      - "$AVATARS_DIR:/usr/share/nginx/html/avatars"

  service:
    build:
      context: .
      dockerfile: Dockerfile.service
    command: flask run --host 0.0.0.0 --port 8080
    container_name: "${REALM}_chat_transit_avatar_service"
    ports:
      - "$PORT:8080"
    environment:
      FLASK_APP: "service.py"
    env_file:
      - .env
    volumes:
      - ./:/build/src
      - "$AVATARS_DIR:/avatars"
