version: "3.8"
services:
  web:
    build: .
    container_name: "${REALM}_chat_transit_discord_relay"
    ports:
      - "127.0.0.1:$PORT:8080"
    env_file:
      - .env
    volumes:
      - ./:/build/src
